if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
  add_compile_options("$<$<CONFIG:DEBUG>:-O0>")
  add_compile_options("$<$<CONFIG:RELEASE>:-O3>")
  add_compile_options("-Wall")
  add_compile_options("-Wextra")
  add_compile_options("-Werror")
  add_compile_options("-msse4.2")
  add_compile_options("-Werror=return-type")
  add_compile_options("-Wno-implicit-fallthrough")
  add_compile_options("-Wno-unused-parameter")
  add_compile_options("-pedantic")

  if (APPLE)
    # without these options on MacOS ld will show up warnings
    add_compile_options("-fvisibility-inlines-hidden")
    add_compile_options("-fvisibility=hidden")
  endif()
endif()
